# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'any_radix_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(373, 312)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputNumLabel = QtWidgets.QLabel(self.centralwidget)
        self.inputNumLabel.setObjectName("inputNumLabel")
        self.verticalLayout.addWidget(self.inputNumLabel)
        self.inputNumField = QtWidgets.QLineEdit(self.centralwidget)
        self.inputNumField.setObjectName("inputNumField")
        self.verticalLayout.addWidget(self.inputNumField)
        self.inputNumRadixLabel = QtWidgets.QLabel(self.centralwidget)
        self.inputNumRadixLabel.setObjectName("inputNumRadixLabel")
        self.verticalLayout.addWidget(self.inputNumRadixLabel)
        self.inputNumRadixField = QtWidgets.QLineEdit(self.centralwidget)
        self.inputNumRadixField.setObjectName("inputNumRadixField")
        self.verticalLayout.addWidget(self.inputNumRadixField)
        self.resultRadixLabel = QtWidgets.QLabel(self.centralwidget)
        self.resultRadixLabel.setObjectName("resultRadixLabel")
        self.verticalLayout.addWidget(self.resultRadixLabel)
        self.resultRadixField = QtWidgets.QLineEdit(self.centralwidget)
        self.resultRadixField.setObjectName("resultRadixField")
        self.verticalLayout.addWidget(self.resultRadixField)
        self.resultLabel = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel.setObjectName("resultLabel")
        self.verticalLayout.addWidget(self.resultLabel)
        self.resultField = QtWidgets.QLineEdit(self.centralwidget)
        self.resultField.setObjectName("resultField")
        self.verticalLayout.addWidget(self.resultField)
        self.separator = QtWidgets.QFrame(self.centralwidget)
        self.separator.setFrameShape(QtWidgets.QFrame.HLine)
        self.separator.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.separator.setObjectName("separator")
        self.verticalLayout.addWidget(self.separator)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.translateButton = QtWidgets.QPushButton(self.centralwidget)
        self.translateButton.setObjectName("translateButton")
        self.horizontalLayout.addWidget(self.translateButton)
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout.addWidget(self.clearButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 373, 26))
        self.menubar.setObjectName("menubar")
        self.fileSubmenu = QtWidgets.QMenu(self.menubar)
        self.fileSubmenu.setObjectName("fileSubmenu")
        self.helpSubmenu = QtWidgets.QMenu(self.menubar)
        self.helpSubmenu.setObjectName("helpSubmenu")
        MainWindow.setMenuBar(self.menubar)
        self.fileExitAction = QtWidgets.QAction(MainWindow)
        self.fileExitAction.setObjectName("fileExitAction")
        self.aboutAction = QtWidgets.QAction(MainWindow)
        self.aboutAction.setObjectName("aboutAction")
        self.fileSubmenu.addAction(self.fileExitAction)
        self.helpSubmenu.addAction(self.aboutAction)
        self.menubar.addAction(self.fileSubmenu.menuAction())
        self.menubar.addAction(self.helpSubmenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AnyRadix"))
        self.inputNumLabel.setText(_translate("MainWindow", "Исходное число:"))
        self.inputNumRadixLabel.setText(_translate("MainWindow", "СС исходного числа:"))
        self.resultRadixLabel.setText(_translate("MainWindow", "СС результата:"))
        self.resultLabel.setText(_translate("MainWindow", "Результат:"))
        self.translateButton.setText(_translate("MainWindow", "Расчёт"))
        self.clearButton.setText(_translate("MainWindow", "Очистить"))
        self.fileSubmenu.setTitle(_translate("MainWindow", "Файл"))
        self.helpSubmenu.setTitle(_translate("MainWindow", "Справка"))
        self.fileExitAction.setText(_translate("MainWindow", "Выход"))
        self.aboutAction.setText(_translate("MainWindow", "Об Авторах"))
